import { BotMessageSquare } from "lucide-react";
import { BatteryCharging } from "lucide-react";
import { Fingerprint } from "lucide-react";
import { ShieldHalf } from "lucide-react";
import { PlugZap } from "lucide-react";
import { GlobeLock } from "lucide-react";

export const navItems = [
  { label: "Home", to: "/" },
  { label: "About", to: "/about" },
  { label: "Periodic Table", to: "/periodic-table" },
  { label: "Contact Us", to: "/contact" },
];


export const features = [
  {
    icon: <BotMessageSquare />,
    text: "Chemistry in robots",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
  },
  {
    icon: <Fingerprint />,
    text: "Forencies",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
  },
  {
    icon: <ShieldHalf />,
    text: "Did you know 3",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
  },
  {
    icon: <BatteryCharging />,
    text: "Playfull Chemistry",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
  },
  {
    icon: <PlugZap />,
    text: "Environmental Chemistry",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
  },
  {
    icon: <GlobeLock />,
    text: "did you know 4",
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.",
  },
];

export const ELEMENTS = [
  {
    id: 1,
    category: 'nonMetal',
    title: 'Non-Metal',
    number: 1,
    weight: '1.008',
    symbol: 'H',
    name: 'Hydrogen',
  },
  {
    id: 2,
    category: 'nobleGas',
    title: 'Noble Gas',
    number: 2,
    weight: '4.0026',
    symbol: 'He',
    name: 'Helium',
  },
  {
    id: 3,
    category: 'alkaliMetal',
    title: 'Alkali Metal',
    number: 3,
    weight: '6.94',
    symbol: 'Li',
    name: 'Lithium',
  },
  {
    id: 4,
    category: 'alkalineEarthMetal',
    title: 'Alkaline Earth Metal',
    number: 4,
    weight: '9.0122',
    symbol: 'Be',
    name: 'Beryllium',
  },
  {
    id: 5,
    category: 'metalloid',
    title: 'Metalloid',
    number: 5,
    weight: '10.81',
    symbol: 'B',
    name: 'Boron',
  },
  {
    id: 6,
    category: 'nonMetal',
    title: 'Non-Metal',
    number: 6,
    weight: '12.011',
    symbol: 'C',
    name: 'Carbon',
  },
  {
    id: 7,
    category: 'nonMetal',
    title: 'Non-Metal',
    number: 7,
    weight: '14.007',
    symbol: 'N',
    name: 'Nitrogen',
  },
  {
    id: 8,
    category: 'nonMetal',
    title: 'Non-Metal',
    number: 8,
    weight: '15.999',
    symbol: 'O',
    name: 'Oxygen',
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    weight: "18.998",
    category: "halogen",
    title: "Halogen",
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    weight: "20.180",
    category: "nobleGas",
    title: "Noble Gas",
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    weight: "22.990",
    category: "alkaliMetal",
    title: "Alkali Metal",
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    weight: "24.305",
    category: "alkalineEarthMetal",
    title: "Alkaline Earth Metal",
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    weight: "26.982",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    weight: "28.085",
    category: "metalloid",
    title: "Metalloid",
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    weight: "30.974",
    category: "nonMetal",
    title: "Non-Metal",
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    weight: "32.06",
    category: "nonMetal",
    title: "Non-Metal",
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    weight: "35.45",
    category: "halogen",
    title: "Halogen",
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    weight: "39.948",
    category: "nobleGas",
    title: "Noble Gas",
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    weight: "39.098",
    category: "alkaliMetal",
    title: "Alkali Metal",
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    weight: "40.078",
    category: "alkalineEarthMetal",
    title: "Alkaline Earth Metal",
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    weight: "44.956",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    weight: "47.867",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    weight: "50.942",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    weight: "51.996",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    weight: "54.938",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    weight: "55.845",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    weight: "58.933",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    weight: "58.693",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    weight: "63.546",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    weight: "65.38",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    weight: "69.723",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    weight: "72.630",
    category: "metalloid",
    title: "Metalloid",
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    weight: "74.922",
    category: "metalloid",
    title: "Metalloid",
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    weight: "78.971",
    category: "nonMetal",
    title: "Non-Metal",
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    weight: "79.904",
    category: "halogen",
    title: "Halogen",
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    weight: "83.798",
    category: "nobleGas",
    title: "Noble Gas",
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    weight: "85.468",
    category: "alkaliMetal",
    title: "Alkali Metal",
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    weight: "87.62",
    category: "alkalineEarthMetal",
    title: "Alkaline Earth Metal",
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    weight: "88.906",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    weight: "91.224",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    weight: "92.906",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    weight: "95.95",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    weight: "[98]",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    weight: "101.07",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    weight: "102.91",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    weight: "106.42",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    weight: "107.87",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    weight: "112.41",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    weight: "114.82",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    weight: "118.71",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    weight: "121.76",
    category: "metalloid",
    title: "Metalloid",
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    weight: "127.60",
    category: "metalloid",
    title: "Metalloid",
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    weight: "126.90",
    category: "halogen",
    title: "Halogen",
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    weight: "131.29",
    category: "nobleGas",
    title: "Noble Gas",
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    weight: "132.91",
    category: "alkaliMetal",
    title: "Alkali Metal",
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    weight: "137.33",
    category: "alkalineEarthMetal",
    title: "Alkaline Earth Metal",
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    weight: "178.49",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    weight: "180.95",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    weight: "183.84",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    weight: "186.21",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    weight: "190.23",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    weight: "192.22",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    weight: "195.08",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    weight: "196.97",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    weight: "200.59",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    weight: "204.38",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    weight: "207.2",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    weight: "208.98",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    weight: "[209]",
    category: "metalloid",
    title: "Metalloid",
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    weight: "[210]",
    category: "halogen",
    title: "Halogen",
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    weight: "[222]",
    category: "nobleGas",
    title: "Noble Gas",
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    weight: "[223]",
    category: "alkaliMetal",
    title: "Alkali Metal",
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    weight: "[226]",
    category: "alkalineEarthMetal",
    title: "Alkaline Earth Metal",
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    weight: "[267]",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    weight: "[270]",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    weight: "[271]",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    weight: "[270]",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    category: "transitionMetal",
    title: "Transition Metal",
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    category: "postTransitionMetal",
    title: "Post Transition Metal",
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    category: "halogen",
    title: "Halogen",
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    category: "nobleGas",
    title: "Noble Gas",
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    category: "lanthanide",
    title: "Lanthanide",
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dyprosium",
    category: "lanthanide"
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    category: "lanthanide"
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    category: "lanthanide"
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    category: "lanthanide"
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    category: "lanthanide"
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    category: "lanthanide"
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    category: "actinide"
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    category: "actinide"
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    category: "actinide"
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    category: "actinide"
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    category: "actinide"
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    category: "actinide"
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    category: "actinide"
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    category: "actinide"
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    category: "actinide"
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    category: "actinide"
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    category: "actinide"
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    category: "actinide"
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    category: "actinide"
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    category: "actinide"
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    category: "actinide"
  }
];

export const resourcesLinks = [
  { href: "#", text: "Getting Started" },
  { href: "#", text: "Newsletter" },
  { href: "#", text: "Our team" },
  { href: "#", text: "Our projects" },
  { href: "#", text: "Query Form" },
];

export const platformLinks = [
  { href: "#", text: "Log In" },
  { href: "#", text: "Github Community" },
  { href: "#", text: "Instagram" },
  { href: "#", text: "LinkedIn" },
];

export const communityLinks = [
  { href: "#", text: "Events" },
  { href: "#", text: "Documentation" },
  { href: "#", text: "Conferences" },
];
